openapi: 3.0.1
info:
  title: Identity Security Cloud v2026 API
  description: Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
  termsOfService: https://developer.sailpoint.com/discuss/tos
  contact:
    name: Developer Relations
    url: https://developer.sailpoint.com/discuss/api-help
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: v2026
servers:
  - url: https://{tenant}.api.identitynow.com/v2026
    description: This is the production API server.
    variables:
      tenant:
        default: sailpoint
        description: This is the name of your tenant, typically your company's name.
  - url: https://{apiUrl}/v2026
    description: This is the v2026 API server.
    variables:
      apiUrl:
        default: sailpoint.api.identitynow.com
        description: This is the api url of your tenant
security:
  - userAuth:
      - sp:scopes:all
tags:
  - name: Task Management
paths:
  /task-status/{id}:
    get:
      tags:
        - Task Management
      summary: Get task status by id
      description: Get task status by task ID. Types of tasks include account and entitlement aggregation and other general background processing tasks.  Data for tasks older than 90 days will not be returned.
      operationId: getTaskStatus
      parameters:
        - name: id
          in: path
          description: Task ID.
          required: true
          x-sailpoint-resource-operation-id: getTaskStatusList
          example: 00eebcf881994e419d72e757fd30dc0e
          style: simple
          explode: false
          schema:
            type: string
        - name: X-SailPoint-Experimental
          in: header
          description: Use this header to enable this experimental API.
          example: true
          schema:
            type: string
            default: true
          required: true
      responses:
        '200':
          description: Responds with a TaskStatus for the task with the given task ID.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskStatus'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          description: Forbidden, generally due to a lack of security rights
        '404':
          description: TaskStatus with the given id was not found.
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      security:
        - userAuth:
            - idn:task-management:read
            - idn:task-management:write
        - applicationAuth:
            - idn:task-management:read
            - idn:task-management:write
      x-sailpoint-userLevels:
        - ORG_ADMIN
        - HELPDESK
        - CERT_ADMIN
        - REPORT_ADMIN
        - ROLE_ADMIN
        - ROLE_SUBADMIN
        - SOURCE_ADMIN
        - SOURCE_SUBADMIN
    patch:
      operationId: updateTaskStatus
      tags:
        - Task Management
      summary: Update task status by id
      description: Update a current task status by task ID. Use this API to clear a pending task by updating the completionStatus and completed attributes.
      parameters:
        - name: id
          in: path
          description: Task ID.
          example: 00eebcf881994e419d72e757fd30dc0e
          required: true
          x-sailpoint-resource-operation-id: getTaskStatusList
          style: simple
          explode: false
          schema:
            type: string
        - name: X-SailPoint-Experimental
          in: header
          description: Use this header to enable this experimental API.
          example: true
          schema:
            type: string
            default: true
          required: true
      requestBody:
        required: true
        description: The JSONPatch payload used to update the object.
        content:
          application/json-patch+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/JsonPatchOperation'
              example:
                - op: replace
                  path: /completionStatus
                  value: Error
                - op: replace
                  path: /completed
                  value: '2024-05-17 19:33:16.470000+00:00'
      responses:
        '200':
          description: This response indicates the PATCH operation succeeded, and the API returns the updated task object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskStatus'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      security:
        - userAuth:
            - idn:task-management:write
      x-sailpoint-userLevels:
        - ORG_ADMIN
        - CERT_ADMIN
        - REPORT_ADMIN
        - ROLE_ADMIN
        - ROLE_SUBADMIN
        - SOURCE_ADMIN
        - SOURCE_SUBADMIN
  /task-status:
    get:
      tags:
        - Task Management
      summary: Retrieve task status list
      description: |
        Use this endpoint to get a list of statuses for **all** tasks which include finished, in-progress, terminated, and errored tasks. Types of tasks include account and entitlement aggregation and other general background processing tasks.  Data for tasks older than 90 days will not be returned. To get a list of statuses for only **in-progress** tasks, please use the [retrieve pending task status list](https://developer.sailpoint.com/docs/api/v2024/get-pending-tasks) endpoint.
        Possible tasks to be returned: Cloud Account Aggregation, Cloud Group Aggregation, Cloud Process Uncorrelated Accounts, Cloud Refresh Role, Source Application Discovery, AI Agent Aggregation, Cloud Entitlement Import, Cloud Uncorrelated Refresh, Cloud Identity Aggregation, Cloud Attribute Synchronization, Identity Refresh
      operationId: getTaskStatusList
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/count'
        - in: query
          name: filters
          schema:
            type: string
          example: type eq "Cloud Account Aggregation" and completionStatus eq "null"
          required: false
          description: |-
            Filter results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#filtering-results)

            Filtering is supported for the following fields and operators:

            **id**: *eq, in*

            **sourceId**: *eq, in*

            **completionStatus**: *eq, in*

            **type**: *eq, in*
        - in: query
          name: sorters
          schema:
            type: string
            format: comma-separated
          example: '-created'
          required: false
          description: |-
            Sort results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#sorting-results)

            Sorting is supported for the following fields: **created**
        - name: X-SailPoint-Experimental
          in: header
          description: Use this header to enable this experimental API.
          example: true
          schema:
            type: string
            default: true
          required: true
      responses:
        '200':
          description: Responds with a TaskStatus for the task with the given task ID.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskStatus'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      security:
        - userAuth:
            - idn:task-management:read
            - idn:task-management:write
        - applicationAuth:
            - idn:task-management:read
            - idn:task-management:write
      x-sailpoint-userLevels:
        - ORG_ADMIN
        - HELPDESK
        - CERT_ADMIN
        - REPORT_ADMIN
        - ROLE_ADMIN
        - ROLE_SUBADMIN
        - SOURCE_ADMIN
        - SOURCE_SUBADMIN
  /task-status/pending-tasks:
    get:
      tags:
        - Task Management
      summary: Retrieve pending task status list
      description: |
        Retrieve a list of statuses for pending tasks. Types of tasks include account and entitlement aggregation and other general background processing tasks.  Data for tasks older than 90 days will not be returned.
        Possible tasks to be returned: Cloud Account Aggregation, Cloud Group Aggregation, Cloud Process Uncorrelated Accounts, Cloud Refresh Role, Source Application Discovery, AI Agent Aggregation, Cloud Entitlement Import, Cloud Uncorrelated Refresh, Cloud Identity Aggregation, Cloud Attribute Synchronization, Identity Refresh
      operationId: getPendingTasks
      parameters:
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/count'
        - name: X-SailPoint-Experimental
          in: header
          description: Use this header to enable this experimental API.
          example: true
          schema:
            type: string
            default: true
          required: true
      responses:
        '200':
          description: Responds with a list of TaskStatus for pending tasks.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskStatus'
        '204':
          $ref: '#/components/responses/204'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      security:
        - userAuth:
            - idn:task-management:read
            - idn:task-management:write
        - applicationAuth:
            - idn:task-management:read
            - idn:task-management:write
      x-sailpoint-userLevels:
        - ORG_ADMIN
        - HELPDESK
        - CERT_ADMIN
        - REPORT_ADMIN
        - ROLE_ADMIN
        - ROLE_SUBADMIN
        - SOURCE_ADMIN
        - SOURCE_SUBADMIN
    head:
      tags:
        - Task Management
      summary: Retrieve pending task list headers
      description: Responds with headers only for list of task statuses for pending tasks.
      operationId: getPendingTaskHeaders
      parameters:
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/count'
        - name: X-SailPoint-Experimental
          in: header
          description: Use this header to enable this experimental API.
          example: true
          schema:
            type: string
            default: true
          required: true
      responses:
        '200':
          description: Retrieve headers for a list of TaskStatus for pending tasks.
        '204':
          $ref: '#/components/responses/204'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      security:
        - userAuth:
            - idn:task-management:read
            - idn:task-management:write
        - applicationAuth:
            - idn:task-management:read
            - idn:task-management:write
      x-sailpoint-userLevels:
        - ORG_ADMIN
        - HELPDESK
        - CERT_ADMIN
        - REPORT_ADMIN
        - ROLE_ADMIN
        - ROLE_SUBADMIN
        - SOURCE_ADMIN
        - SOURCE_SUBADMIN
components:
  securitySchemes:
    userAuth:
      type: oauth2
      x-displayName: Personal Access Token
      description: |
        OAuth2 Bearer token (JWT) generated using either a [personal access token (PAT)](https://developer.sailpoint.com/docs/api/authentication/#generate-a-personal-access-token) or through the [authorization code flow](https://developer.sailpoint.com/docs/api/authentication/#request-access-token-with-authorization-code-grant-flow).

        Personal access tokens are associated with a user in Identity Security Cloud and relies on the user's [user level](https://documentation.sailpoint.com/saas/help/common/users/index.html) (ex. Admin, Helpdesk, etc.) to determine a base level of access.

        See [Identity Security Cloud REST API Authentication](https://developer.sailpoint.com/docs/api/authentication/) for more information.
      flows:
        clientCredentials:
          tokenUrl: https://example-tenant.api.identitynow.com/oauth/token
          scopes:
            sp:scopes:default: default scope
            sp:scopes:all: access to all scopes
        authorizationCode:
          authorizationUrl: https://example-tenant.login.sailpoint.com/oauth/authorize
          tokenUrl: https://example-tenant.api.identitynow.com/oauth/token
          scopes:
            sp:scopes:default: default scope
            sp:scopes:all: access to all scopes
    applicationAuth:
      type: oauth2
      x-displayName: Client Credentials
      description: |
        OAuth2 Bearer token (JWT) generated using [client credentials flow](https://developer.sailpoint.com/docs/api/authentication/#request-access-token-with-client-credentials-grant-flow).

        Client credentials refers to tokens that are not associated with a user in Identity Security Cloud.

        See [Identity Security Cloud REST API Authentication](https://developer.sailpoint.com/docs/api/authentication/) for more information.
      flows:
        clientCredentials:
          tokenUrl: https://example-tenant.api.identitynow.com/oauth/token
          scopes:
            sp:scopes:default: default scope
            sp:scopes:all: access to all scopes
  schemas:
    Target:
      type: object
      title: Target
      nullable: true
      properties:
        id:
          description: Target ID
          type: string
          example: c6dc37bf508149b28ce5b7d90ca4bbf9
        type:
          description: Target type
          type: string
          nullable: true
          enum:
            - APPLICATION
            - IDENTITY
            - null
          example: APPLICATION
        name:
          description: Target name
          type: string
          example: Active Directory [source]
    LocalizedMessage:
      type: object
      title: Localized Message
      nullable: true
      description: Localized error message to indicate a failed invocation or error if any.
      required:
        - locale
        - message
      properties:
        locale:
          description: Message locale
          type: string
          example: An error has occurred!
        message:
          description: Message text
          type: string
          example: Error has occurred!
    TaskStatusMessage:
      description: TaskStatus Message
      required:
        - key
        - localizedText
        - type
        - parameters
      type: object
      title: Task Status Message
      properties:
        type:
          description: Type of the message
          type: string
          enum:
            - INFO
            - WARN
            - ERROR
          example: INFO
        localizedText:
          description: Localized form of the message
          $ref: '#/components/schemas/LocalizedMessage'
        key:
          description: Key of the message
          type: string
          example: akey
        parameters:
          description: Message parameters for internationalization
          nullable: true
          type: array
          items:
            anyOf:
              - type: object
              - type: string
          example:
            - name: value
    TaskReturnDetails:
      description: Task return details
      required:
        - name
        - attributeName
      type: object
      title: Task Return Details
      properties:
        name:
          description: Display name of the TaskReturnDetails
          type: string
          example: label
        attributeName:
          description: Attribute the TaskReturnDetails is for
          type: string
          example: identityCount
    TaskDefinitionSummary:
      description: Definition of a type of task, used to invoke tasks
      required:
        - arguments
        - description
        - executor
        - id
        - uniqueName
        - parentName
      type: object
      title: Task Definition Summary
      properties:
        id:
          description: System-generated unique ID of the TaskDefinition
          type: string
          example: 2c91808475b4334b0175e1dff64b63c5
        uniqueName:
          description: Name of the TaskDefinition
          type: string
          example: Cloud Account Aggregation
        description:
          nullable: true
          description: Description of the TaskDefinition
          type: string
          example: Aggregates from the specified application.
        parentName:
          description: Name of the parent of the TaskDefinition
          type: string
          example: Cloud Account Aggregation
        executor:
          description: Executor of the TaskDefinition
          nullable: true
          type: string
          example: sailpoint.task.ServiceTaskExecutor
        arguments:
          description: Formal parameters of the TaskDefinition, without values
          type: object
          additionalProperties: true
          example:
            mantisExecutor: com.sailpoint.mantis.sources.task.AccountAggregationTask
            eventClassesCsv: sailpoint.thunderbolt.events.AggregationEvents
            serviceClass: sailpoint.thunderbolt.service.AggregationService
            serviceMethod: accountAggregationTask
    TaskStatus:
      description: Details and current status of a specific task
      required:
        - id
        - type
        - uniqueName
        - description
        - parentName
        - attributes
        - created
        - modified
        - launched
        - launcher
        - completed
        - completionStatus
        - messages
        - progress
        - percentComplete
        - returns
      type: object
      title: Task Status
      properties:
        id:
          description: System-generated unique ID of the task this TaskStatus represents
          type: string
          example: id12345
        type:
          description: Type of task this TaskStatus represents
          type: string
          enum:
            - QUARTZ
            - QPOC
            - QUEUED_TASK
          example: QUARTZ
        uniqueName:
          description: Name of the task this TaskStatus represents
          type: string
          example: Big Task
        description:
          description: Description of the task this TaskStatus represents
          type: string
          example: A Really Big Task
        parentName:
          description: Name of the parent of the task this TaskStatus represents
          nullable: true
          type: string
          example: Parent Task
        launcher:
          description: Service to execute the task this TaskStatus represents
          type: string
          example: sweep
        target:
          $ref: '#/components/schemas/Target'
        created:
          description: Creation date of the task this TaskStatus represents
          type: string
          format: date-time
          example: '2020-07-11T21:23:15.000Z'
        modified:
          description: Last modification date of the task this TaskStatus represents
          type: string
          format: date-time
          example: '2020-07-11T21:23:15.000Z'
        launched:
          description: Launch date of the task this TaskStatus represents
          nullable: true
          type: string
          format: date-time
          example: '2020-07-11T21:23:15.000Z'
        completed:
          description: Completion date of the task this TaskStatus represents
          nullable: true
          type: string
          format: date-time
          example: '2020-07-11T21:23:15.000Z'
        completionStatus:
          description: Completion status of the task this TaskStatus represents
          type: string
          nullable: true
          enum:
            - SUCCESS
            - WARNING
            - ERROR
            - TERMINATED
            - TEMPERROR
            - null
          example: SUCCESS
        messages:
          description: Messages associated with the task this TaskStatus represents
          type: array
          items:
            $ref: '#/components/schemas/TaskStatusMessage'
        returns:
          description: Return values from the task this TaskStatus represents
          type: array
          items:
            $ref: '#/components/schemas/TaskReturnDetails'
        attributes:
          description: Attributes of the task this TaskStatus represents
          type: object
          additionalProperties: true
          example:
            identityCount: 0
        progress:
          description: Current progress of the task this TaskStatus represents
          nullable: true
          type: string
          example: Started
        percentComplete:
          description: Current percentage completion of the task this TaskStatus represents
          type: integer
          format: int32
          example: 100
        taskDefinitionSummary:
          $ref: '#/components/schemas/TaskDefinitionSummary'
    LocaleOrigin:
      type: string
      enum:
        - DEFAULT
        - REQUEST
        - null
      description: An indicator of how the locale was selected. *DEFAULT* means the locale is the system default. *REQUEST* means the locale was selected from the request context (i.e., best match based on the *Accept-Language* header). Additional values may be added in the future without notice.
      example: DEFAULT
      nullable: true
    ErrorMessageDto:
      type: object
      title: Error Message Dto
      properties:
        locale:
          type: string
          description: The locale for the message text, a BCP 47 language tag.
          example: en-US
          nullable: true
        localeOrigin:
          $ref: '#/components/schemas/LocaleOrigin'
        text:
          type: string
          description: Actual text of the error message in the indicated locale.
          example: The request was syntactically correct but its content is semantically invalid.
    ErrorResponseDto:
      type: object
      title: Error Response Dto
      properties:
        detailCode:
          type: string
          description: Fine-grained error code providing more detail of the error.
          example: 400.1 Bad Request Content
        trackingId:
          type: string
          description: Unique tracking id for the error.
          example: e7eab60924f64aa284175b9fa3309599
        messages:
          type: array
          description: Generic localized reason for error
          items:
            $ref: '#/components/schemas/ErrorMessageDto'
        causes:
          type: array
          description: Plain-text descriptive reasons to provide additional detail to the text provided in the messages field
          items:
            $ref: '#/components/schemas/ErrorMessageDto'
    JsonPatchOperation:
      type: object
      title: Json Patch Operation
      description: A JSONPatch Operation as defined by [RFC 6902 - JSON Patch](https://tools.ietf.org/html/rfc6902)
      required:
        - op
        - path
      properties:
        op:
          type: string
          description: The operation to be performed
          enum:
            - add
            - remove
            - replace
            - move
            - copy
            - test
          example: replace
        path:
          type: string
          description: A string JSON Pointer representing the target path to an element to be affected by the operation
          example: /description
        value:
          oneOf:
            - type: string
              example: New description
              title: string
            - type: boolean
              example: true
              title: boolean
            - type: integer
              example: 300
              title: integer
            - type: object
              title: object
              example:
                attributes:
                  name: philip
            - type: array
              title: array
              items:
                anyOf:
                  - type: string
                  - type: integer
                  - type: object
                example:
                  - '001'
                  - '002'
                  - '003'
          description: The value to be used for the operation, required for "add" and "replace" operations
          example: New description
  responses:
    '204':
      description: No content - indicates the request was successful but there is no content to be returned in the response.
    '400':
      description: Client Error - Returned if the request body is invalid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseDto'
    '401':
      description: Unauthorized - Returned if there is no authorization header, or if the JWT token is expired.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                description: A message describing the error
                example: 'JWT validation failed: JWT is expired'
    '403':
      description: Forbidden - Returned if the user you are running as, doesn't have access to this end-point.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseDto'
          examples:
            '403':
              summary: An example of a 403 response object
              value:
                detailCode: 403 Forbidden
                trackingId: b21b1f7ce4da4d639f2c62a57171b427
                messages:
                  - locale: en-US
                    localeOrigin: DEFAULT
                    text: The server understood the request but refuses to authorize it.
    '404':
      description: Not Found - returned if the request URL refers to a resource or object that does not exist
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseDto'
          examples:
            '404':
              summary: An example of a 404 response object
              value:
                detailCode: 404 Not found
                trackingId: b21b1f7ce4da4d639f2c62a57171b427
                messages:
                  - locale: en-US
                    localeOrigin: DEFAULT
                    text: The server did not find a current representation for the target resource.
    '429':
      description: Too Many Requests - Returned in response to too many requests in a given period of time - rate limited. The Retry-After header in the response includes how long to wait before trying again.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                description: A message describing the error
                example: ' Rate Limit Exceeded '
    '500':
      description: Internal Server Error - Returned if there is an unexpected error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseDto'
          examples:
            '500':
              summary: An example of a 500 response object
              value:
                detailCode: 500.0 Internal Fault
                trackingId: b21b1f7ce4da4d639f2c62a57171b427
                messages:
                  - locale: en-US
                    localeOrigin: DEFAULT
                    text: An internal fault occurred.
  parameters:
    limit:
      in: query
      name: limit
      description: |-
        Max number of results to return.
        See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
      required: false
      example: 250
      schema:
        type: integer
        format: int32
        minimum: 0
        maximum: 250
        default: 250
    offset:
      in: query
      name: offset
      description: |-
        Offset into the full result set. Usually specified with *limit* to paginate through the results.
        See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
      required: false
      example: 0
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 0
    count:
      in: query
      name: count
      description: |-
        If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.

        Since requesting a total count can have a performance impact, it is recommended not to send **count=true** if that value will not be used.

        See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
      required: false
      example: true
      schema:
        type: boolean
        default: false
